#!/bin/sh
# Copyright 2024 Collabora Ltd.
# SPDX-License-Identifier: MIT

set -eu

for arg in "$@"; do
    case "$arg" in
        (--share-pids)
            echo "$0: emulating flatpak with setuid bwrap" >&2
            exit 1
            ;;

        (*DISPLAY*)
            echo "DISPLAY_is_set"
            ;;
    esac
done

exit 0
