#!/bin/sh
# Copyright 2024 Collabora Ltd.
# SPDX-License-Identifier: MIT

set -eu

for arg in "$@"; do
    case "$arg" in
        (*DISPLAY*)
            echo "DISPLAY_is_set"
            ;;
    esac
done

exit 0
