#!/bin/sh
# Copyright 2024 Collabora Ltd.
# SPDX-License-Identifier: MIT

set -eu

for arg in "$@"; do
    case "$arg" in
        (*--perms*)
            echo "$0: does not support --perms"
            exit 2
            ;;
    esac
done

exit 0
